const cardsArray = [

    //JOKER
    {
        name: "Joker Color",
        type: "Joker",
        rank: 14,
        img: "images/joker_color.png",
        front: "front_black.png",
    },
    {
        name: "Joker Black",
        type: "Joker",
        rank: 15,
        img: "joker_black.png",
        front: "front_black.png",
    },
    //HEARTS
    {
        name: "Hearts Ace",
        type: "Hearts",
        rank: 14,
        img: "hearts_ace.png",
        front: "front_black.png",
    },
    {
        name: "Hearts King",
        type: "Hearts",
        rank: 13,
        img: "hearts_king.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Queen",
        type: "Hearts",
        rank: 12,
        img: "hearts_queen.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Knight",
        type: "Hearts",
        rank: 11,
        img: "hearts_knight.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Ten",
        type: "Hearts",
        rank: 10,
        img: "hearts_ten.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Nine",
        type: "Hearts",
        rank: 9,
        img: "hearts_nine.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Eight",
        type: "Hearts",
        rank: 8,
        img: "hearts_eight.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Seven",
        type: "Hearts",
        rank: 7,
        img: "hearts_seven.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Six",
        type: "Hearts",
        rank: 6,
        img: "hearts_six.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Five",
        type: "Hearts",
        rank: 5,
        img: "hearts_five.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Four",
        type: "Hearts",
        rank: 4,
        img: "hearts_four.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Three",
        type: "Hearts",
        rank: 3,
        img: "hearts_three.png",
        front: "front_black.png",
    },
    {
        name: "Hearts Two",
        type: "Joker",
        rank: 2,
        img: "hearts_two.png",
        front: "front_black.png",
    },
    //SPADES
    {
        name: "spades Ace",
        type: "spades",
        rank: 14,
        img: "spades_ace.png",
        front: "front_black.png",
    },
    {
        name: "spades King",
        type: "spades",
        rank: 13,
        img: "spades_king.png",
        front: "front_black.png",
    },
    {
        name: "spades Queen",
        type: "spades",
        rank: 12,
        img: "spades_queen.png",
        front: "front_black.png",
    },
    {
        name: "spades Knight",
        type: "spades",
        rank: 11,
        img: "spades_knight.png",
        front: "front_black.png",
    },
    {
        name: "spades Ten",
        type: "spades",
        rank: 10,
        img: "spades_ten.png",
        front: "front_black.png",
    },
    {
        name: "spades Nine",
        type: "spades",
        rank: 9,
        img: "spades_nine.png",
        front: "front_black.png",
    },
    {
        name: "spades Eight",
        type: "spades",
        rank: 8,
        img: "spades_eight.png",
        front: "front_black.png",
    },
    {
        name: "spades Seven",
        type: "spades",
        rank: 7,
        img: "spades_seven.png",
        front: "front_black.png",
    },
    {
        name: "spades Six",
        type: "spades",
        rank: 6,
        img: "spades_six.png",
        front: "front_black.png",
    },
    {
        name: "spades Five",
        type: "spades",
        rank: 5,
        img: "spades_five.png",
        front: "front_black.png",
    },
    {
        name: "spades Four",
        type: "spades",
        rank: 4,
        img: "spades_four.png",
        front: "front_black.png",
    },
    {
        name: "spades Three",
        type: "Spades",
        rank: 3,
        img: "spades_three.png",
        front: "front_black.png",
    },
    {
        name: "spades Two",
        type: "Spades",
        rank: 2,
        img: "spades_two.png",
        front: "front_black.png",
    },

    //DIAMONDS
    {
        name: "diamonds Ace",
        type: "diamonds",
        rank: 14,
        img: "diamonds_ace.png",
        front: "front_black.png",
    },
    {
        name: "diamonds King",
        type: "diamonds",
        rank: 13,
        img: "diamonds_king.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Queen",
        type: "diamonds",
        rank: 12,
        img: "diamonds_queen.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Knight",
        type: "diamonds",
        rank: 11,
        img: "diamonds_knight.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Ten",
        type: "diamonds",
        rank: 10,
        img: "diamonds_ten.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Nine",
        type: "diamonds",
        rank: 9,
        img: "diamonds_nine.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Eight",
        type: "diamonds",
        rank: 8,
        img: "diamonds_eight.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Seven",
        type: "diamonds",
        rank: 7,
        img: "diamonds_seven.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Six",
        type: "diamonds",
        rank: 6,
        img: "diamonds_six.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Five",
        type: "diamonds",
        rank: 5,
        img: "diamonds_five.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Four",
        type: "diamonds",
        rank: 4,
        img: "diamonds_four.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Three",
        type: "diamonds",
        rank: 3,
        img: "diamonds_three.png",
        front: "front_black.png",
    },
    {
        name: "diamonds Two",
        type: "diamonds",
        rank: 2,
        img: "diamonds_two.png",
        front: "front_black.png",
    },
    //CLUBS
    {
        name: "clubs Ace",
        type: "clubs",
        rank: 14,
        img: "clubs_ace.png",
        front: "front_black.png",
    },
    {
        name: "clubs King",
        type: "clubs",
        rank: 13,
        img: "clubs_king.png",
        front: "front_black.png",
    },
    {
        name: "clubs Queen",
        type: "clubs",
        rank: 12,
        img: "clubs_queen.png",
        front: "front_black.png",
    },
    {
        name: "clubs Knight",
        type: "clubs",
        rank: 11,
        img: "clubs_knight.png",
        front: "front_black.png",
    },
    {
        name: "clubs Ten",
        type: "clubs",
        rank: 10,
        img: "clubs_ten.png",
        front: "front_black.png",
    },
    {
        name: "clubs Nine",
        type: "clubs",
        rank: 9,
        img: "clubs_nine.png",
        front: "front_black.png",
    },
    {
        name: "clubs Eight",
        type: "clubs",
        rank: 8,
        img: "clubs_eight.png",
        front: "front_black.png",
    },
    {
        name: "clubs Seven",
        type: "clubs",
        rank: 7,
        img: "clubs_seven.png",
        front: "front_black.png",
    },
    {
        name: "clubs Six",
        type: "clubs",
        rank: 6,
        img: "clubs_six.png",
        front: "front_black.png",
    },
    {
        name: "clubs Five",
        type: "clubs",
        rank: 5,
        img: "clubs_five.png",
        front: "front_black.png",
    },
    {
        name: "clubs Four",
        type: "clubs",
        rank: 4,
        img: "clubs_four.png",
        front: "front_black.png",
    },
    {
        name: "clubs Three",
        type: "clubs",
        rank: 3,
        img: "clubs_three.png",
        front: "front_black.png",
    },
    {
        name: "clubs Two",
        type: "clubs",
        rank: 2,
        img: "clubs_two.png",
        front: "front_black.png",
    },
];

export default cardsArray;